# -*- coding: utf-8 -*-
"""CodeAlpha_Basic_Chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bj1qcsyXmkFj1DwjlPUdG0_n1XkvZpSa
"""

print("🤖 Welcome to My Chatbot")

message = input("You: ")

print("Bot:", message)

message = input("You: ").lower()

if message == "hello":
    print("Bot: Hi! How are you?")

message = input("You: ").lower()

if message == "hello":
    print("Bot: Hi!")

elif message == "bye":
    print("Bot: Goodbye!")

message = input("You: ").lower()

if message == "hello":
    print("Bot: Hi! 👋")

elif message == "how are you":
    print("Bot: I am fine, thanks! 😊")

elif message == "what is your name":
    print("Bot: My name is CodeBot.")

elif message == "bye":
    print("Bot: Goodbye! Have a nice day. 👋")

else:
    print("Bot: Sorry, I don't understand.")

print("=" * 40)
print("🤖 Welcome to CodeBot")
print("Type 'bye' to exit")
print("=" * 40)

while True:

    message = input("\nYou: ").lower()

    if message == "hello":
        print("Bot: Hi! 👋")

    elif message == "how are you":
        print("Bot: I am fine, thanks! 😊")

    elif message == "what is your name":
        print("Bot: My name is CodeBot.")

    elif message == "good morning":
        print("Bot: Good Morning! 🌞")

    elif message == "thank you":
        print("Bot: You're Welcome! 😊")

    elif message == "bye":
        print("Bot: Goodbye! Have a Nice Day. 👋")
        break

    else:
        print("Bot: Sorry, I don't understand.")